In [24]:
import pandas as pd
import numpy as np
import os

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [25]:
home = os.path.expanduser("~")
df = pd.read_csv(f"{home}/credit-risk-ml-system/data/raw/Credit_score_cleaned_data.csv")
df.head()

,Customer_ID,Age,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Delay_from_due_date,...,Last_Loan_9,Last_Loan_8,Last_Loan_7,Last_Loan_6,Last_Loan_5,Last_Loan_4,Last_Loan_3,Last_Loan_2,Last_Loan_1,Credit_Score
0,CUS_0x98ed,31,Journalist,22229.060,1672.421667,6,4,5.0,3,10,...,No Loan,No Loan,No Loan,No Loan,No Loan,No Loan,Debt Consolidation Loan,Home Equity Loan,Debt Consolidation Loan,Standard
1,CUS_0x36b4,43,Musician,17060.705,1685.725417,8,3,11.0,4,24,...,No Loan,No Loan,No Loan,No Loan,No Loan,Debt Consolidation Loan,Home Equity Loan,Auto Loan,Auto Loan,Standard
2,CUS_0x105b,24,Accountant,34428.210,2575.017500,2,4,8.0,0,3,...,No Loan,No Loan,No Loan,No Loan,No Loan,No Loan,No Loan,No Loan,No Loan,Good
3,CUS_0x4c4a,21,Accountant,12613.920,1155.160000,4,6,13.0,3,14,...,No Loan,No Loan,No Loan,No Loan,No Loan,No Loan,Personal Loan,Student Loan,Home Equity Loan,Standard
4,CUS_0x612f,31,Journalist,34775.160,3048.930000,7,9,25.0,5,20,...,No Loan,No Loan,No Loan,No Loan,Auto Loan,Mortgage Loan,Auto Loan,Payday Loan,Not Specified,Poor

In [26]:
df = df.drop(columns=["Customer_ID"])

In [27]:
score_map = {
    "Poor":0,
    "Standard":1,
    "Good":2
}

df["Credit_Score"] = df["Credit_Score"].map(score_map)

In [28]:
df["Credit_Score"].value_counts()

Credit_Score
1    53174
0    28998
2    17828
Name: count, dtype: int64

In [29]:
loan_cols = [
"Last_Loan_1","Last_Loan_2","Last_Loan_3","Last_Loan_4",
"Last_Loan_5","Last_Loan_6","Last_Loan_7","Last_Loan_8","Last_Loan_9"
]

In [30]:
df["num_auto_loans"] = df[loan_cols].apply(
    lambda x: (x == "Auto Loan").sum(),
    axis=1
)

In [31]:
df["num_mortgage_loans"] = df[loan_cols].apply(
    lambda x: (x == "Mortgage Loan").sum(),
    axis=1
)

In [32]:
df["num_student_loans"] = df[loan_cols].apply(
    lambda x: (x == "Student Loan").sum(),
    axis=1
)

In [33]:
df = df.drop(columns=loan_cols)

In [34]:
df.head()

,Age,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,...,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score,num_auto_loans,num_mortgage_loans,num_student_loans
0,31,Journalist,22229.060,1672.421667,6,4,5.0,3,10,10,...,156,Yes,52.138474,44.084010,High_spent_Medium_value_payments,321.019683,1,0,0,0
1,43,Musician,17060.705,1685.725417,8,3,11.0,4,24,8,...,269,Yes,51.934634,39.628311,Low_spent_Small_value_payments,327.009597,1,2,0,0
2,24,Accountant,34428.210,2575.017500,2,4,8.0,0,3,12,...,326,No,0.000000,84.774645,High_spent_Small_value_payments,432.727105,2,0,0,0
3,21,Accountant,12613.920,1155.160000,4,6,13.0,3,14,17,...,376,Yes,16.941903,41.943603,Low_spent_Medium_value_payments,346.630494,1,0,0,1
4,31,Journalist,34775.160,3048.930000,7,9,25.0,5,20,20,...,162,Yes,126.596814,67.970377,High_spent_Medium_value_payments,360.325808,0,2,1,0

In [35]:
cat_cols = df.select_dtypes(include="object").columns
cat_cols

Index(['Occupation', 'Credit_Mix', 'Payment_of_Min_Amount',
       'Payment_Behaviour'],
      dtype='object')

In [36]:
le = LabelEncoder()

for col in cat_cols:
    df[col] = le.fit_transform(df[col])

In [37]:
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Age                       100000 non-null  int64
 1   Occupation                100000 non-null  int64
 2   Annual_Income             100000 non-null  float64
 3   Monthly_Inhand_Salary     100000 non-null  float64
 4   Num_Bank_Accounts         100000 non-null  int64
 5   Num_Credit_Card           100000 non-null  int64
 6   Interest_Rate             100000 non-null  float64
 7   Num_of_Loan               100000 non-null  int64
 8   Delay_from_due_date       100000 non-null  int64
 9   Num_of_Delayed_Payment    100000 non-null  int64
 10  Changed_Credit_Limit      100000 non-null  float64
 11  Num_Credit_Inquiries      100000 non-null  int64
 12  Credit_Mix                100000 non-null  int64
 13  Outstanding_Debt          100000 non-null  float64
 14  Credit_Utilization_Ratio  100000 non-null  float64
 15  Credit_History_Age        100000 non-null  int64
 16  Payment_of_Min_Amount     100000 non-null  int64
 17  Total_EMI_per_month       100000 non-null  float64
 18  Amount_invested_monthly   100000 non-null  float64
 19  Payment_Behaviour         100000 non-null  int64
 20  Monthly_Balance           100000 non-null  float64
 21  Credit_Score              100000 non-null  int64
 22  num_auto_loans            100000 non-null  int64
 23  num_mortgage_loans        100000 non-null  int64
 24  num_student_loans         100000 non-null  int64
dtypes: float64(9), int64(16)
memory usage: 19.1 MB

In [38]:
X = df.drop(columns=["Credit_Score"])
y = df["Credit_Score"]

In [39]:
from sklearn.model_selection import train_test_split

# 1. Разделяем на train + temp (validation + test)
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.3, random_state=42
)

# 2. Разделяем temp на validation и test
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, random_state=42
)

print(X_train.shape, X_val.shape, X_test.shape)

(70000, 24) (15000, 24) (15000, 24)

In [40]:
num_features = [
    'Age', 'Annual_Income', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts', 
    'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan', 'Delay_from_due_date',
    'Num_of_Delayed_Payment', 'Changed_Credit_Limit', 'Num_Credit_Inquiries',
    'Outstanding_Debt', 'Credit_Utilization_Ratio', 'Credit_History_Age', 
    'Total_EMI_per_month', 'Amount_invested_monthly', 'Monthly_Balance'
]

In [41]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train[num_features])
X_val_scaled = scaler.transform(X_val[num_features])
X_test_scaled = scaler.transform(X_test[num_features])

In [42]:
X_train_scaled = pd.DataFrame(X_train_scaled, columns=num_features, index=X_train.index)
X_val_scaled = pd.DataFrame(X_val_scaled, columns=num_features, index=X_val.index)
X_test_scaled = pd.DataFrame(X_test_scaled, columns=num_features, index=X_test.index)

In [43]:
X_train_scaled['Debt_to_Income'] = X_train['Outstanding_Debt'] / X_train['Annual_Income']
X_val_scaled['Debt_to_Income'] = X_val['Outstanding_Debt'] / X_val['Annual_Income']
X_test_scaled['Debt_to_Income'] = X_test['Outstanding_Debt'] / X_test['Annual_Income']

X_train_scaled['EMI_to_Income'] = X_train['Total_EMI_per_month'] / X_train['Monthly_Inhand_Salary']
X_val_scaled['EMI_to_Income'] = X_val['Total_EMI_per_month'] / X_val['Monthly_Inhand_Salary']
X_test_scaled['EMI_to_Income'] = X_test['Total_EMI_per_month'] / X_test['Monthly_Inhand_Salary']

In [45]:
X_train_scaled['Active_Loans'] = X_train['Num_of_Loan']
X_val_scaled['Active_Loans'] = X_val['Num_of_Loan']
X_test_scaled['Active_Loans'] = X_test['Num_of_Loan']

In [47]:
X_train_scaled['Occupation_CreditMix'] = X_train['Occupation'].astype(str) + '_' + X_train['Credit_Mix'].astype(str)
X_val_scaled['Occupation_CreditMix'] = X_val['Occupation'].astype(str) + '_' + X_val['Credit_Mix'].astype(str)
X_test_scaled['Occupation_CreditMix'] = X_test['Occupation'].astype(str) + '_' + X_test['Credit_Mix'].astype(str)

In [49]:
os.makedirs("../data/processed", exist_ok=True)

X_train_scaled.to_csv("../data/processed/X_train.csv", index=False)
y_train.to_csv("../data/processed/y_train.csv", index=False)

X_val_scaled.to_csv("../data/processed/X_val.csv", index=False)
y_val.to_csv("../data/processed/y_val.csv", index=False)

X_test_scaled.to_csv("../data/processed/X_test.csv", index=False)
y_test.to_csv("../data/processed/y_test.csv", index=False)